import {showToast} from "./utils.js"; import {api} from "./api.js"; import {openYouTube} from "./youtube.js";
let recognition,listening=false;
export function renderVoice(container){container.innerHTML=`<div class="two-col"><div class="view-card"><h3>Voice Assistant</h3><p class="sub">Say complete commands. AURA can open tools and perform actions for you.</p><div style="display:grid;place-items:center;min-height:270px"><button id="voiceOrb" class="ai-core" style="border:0;background:transparent;cursor:pointer" aria-label="Start voice assistant"><div class="core-glow"></div><div class="robot-face"><span class="eye left-eye"></span><span class="eye right-eye"></span><div class="robot-mouth"></div></div><div class="core-label">TAP TO SPEAK</div></button></div><div id="voiceStatus" class="result-box">Try: “Open YouTube and search for Python tutorials.”</div></div><div class="view-card"><h3>Command examples</h3><div class="result-box">“Open Weather in Pune”<br><br>“Open YouTube and search for JavaScript tutorials”<br><br>“Open Tasks and add a task finish my project at 6 PM”<br><br>“Open AI Chat”</div><textarea id="voiceText" class="form-input" style="height:120px;padding:14px;resize:vertical" placeholder="Voice transcript…"></textarea><div class="control-row" style="margin-top:12px"><button class="primary-btn" id="speakBtn"><i class="icon icon-volume-2"></i> Speak response</button><button class="outline-btn" id="stopSpeakBtn">Stop</button></div></div></div>`;
 const status=document.getElementById("voiceStatus"),orb=document.getElementById("voiceOrb");
 orb.onclick=()=>{if(listening){recognition?.stop();return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return showToast("Speech recognition is not available in this browser.");recognition=new R();recognition.lang="en-IN";recognition.interimResults=true;recognition.continuous=false;listening=true;status.textContent="Listening…";recognition.onresult=e=>{const text=[...e.results].map(x=>x[0].transcript).join("");document.getElementById("voiceText").value=text;status.textContent=text;if(e.results[e.results.length-1].isFinal) execute(text)};recognition.onerror=e=>status.textContent=`Voice error: ${e.error}`;recognition.onend=()=>{listening=false;orb.style.transform=""};orb.style.transform="scale(1.06)";recognition.start()};
 document.getElementById("speakBtn").onclick=()=>{const t=document.getElementById("voiceStatus").textContent;speak(t)};document.getElementById("stopSpeakBtn").onclick=()=>speechSynthesis.cancel();
}
async function execute(text){const status=document.getElementById("voiceStatus");try{const result=await api("/command",{method:"POST",body:JSON.stringify({text})});if(result.action==="youtube_search"){status.textContent=`Opening YouTube and searching for “${result.query}”…`;speak(`Opening YouTube and searching for ${result.query}`);setTimeout(()=>openYouTube(result.query),300);return}if(result.action==="create_task"){status.textContent=`Task added: ${result.task.text}${result.task.reminder_at?" with a reminder":""}.`;speak("Task added successfully.");return}if(result.action==="open_tool"){status.textContent=`Opening ${result.tool}…`;speak(`Opening ${result.tool}`);setTimeout(()=>location.href=`tool.html?tool=${encodeURIComponent(result.tool)}${result.city?`&city=${encodeURIComponent(result.city)}`:""}`,300);return}if(result.action==="chat"){status.textContent="Sending that to AI Chat…";const chat=await api("/chat",{method:"POST",body:JSON.stringify({messages:[{role:"user",content:result.text}]})});status.textContent=chat.content;speak(chat.content);return}}catch(e){status.textContent=e.message;speak(e.message)}}
function speak(text){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text));}
